name: "ğŸ­ Pipeline"

on: push

jobs:
  lint:
    name: "ğŸ§¹ğŸ§ª Lint/Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: "bun install --ignore-scripts"
      - run: "bun lint && bun test"
